
export interface School {
  _id: string;
  name: string;
  location: string;
  contactEmail: string;
  contactNumber: string;
  numberOfStudents: number;
  createdAt: string;
  updatedAt: string;
}

export interface Transaction {
  _id: string;
  schoolId: string;
  studentId?: string;
  type: 'income' | 'expense';
  category: string;
  amount: number;
  date: string;
  description: string;
  createdAt: string;
  updatedAt: string;
}

export interface User {
  _id: string; // Map `id` from the response to `_id`
  email: string;
  role:string;
  createdAt?: string; // Optional, since it's not returned in the login response
  updatedAt?: string; // Optional, since it's not returned in the login response
}

export interface AuthState {
  isAuthenticated: boolean;
  user: User | null;
  token: string | null;
  loading: boolean;
  error: string | null;
}

export interface SchoolFinancial {
  school: School;
  netBalance: number;
  totalIncome: number;
  totalExpense: number;
  transactions: Transaction[];
}

export interface Category {
  id: string;
  name: string;
  type: 'income' | 'expense';
}

export interface Student {
  _id?: string; // Optional, as it will be generated by the backend
  name: string; // Mandatory
  class: string; // Mandatory
  contact: string; // Mandatory
  emailId?: string; // Optional
  address?: string; // Optional
  details?: string; // Optional
  dateOfBirth: string; //
  dateOfAdmission: string; 
  fatherName?: string; // Optional
  motherName?: string; // Optional
  fatherPhone?: string; // Optional
  motherPhone?: string; // Optional
  imageUrl?: string;
}

export interface Category {
  _id?: string; 
  name: string; 
  description?: string;
  createdAt?: string;
  totalInvestment?: number;
}

export interface Item {
  _id?: string; 
  name: string; 
  description?: string;
  quantity: number; 
  price: number;
  category_id: string; 
  createdAt?: string;
  updatedAt?: string
}

export interface SchoolItem {
  schoolId: string;
  itemId: string;
  quantity: number;
  price: number;
  createdAt: Date;
}
